import { Employee } from "@/types/employee";

export const MOCK_EMPLOYEES: Employee[] = [
  {
    employeeId: "EMP3930",
    name: "Shah Alam",
    category: "sales",
    department: "Sales",
    doj: "2026-01-05",
    tenureDays: 91,
    reportingManager: "Imran Mr",
    feedback: {
      d30: { rating: null, areaOfStrength: null, areaOfImprovement: null, comment:"Continue & Hardworking. Problem solving approach.", postedOn: "03 Feb 2026", quality: null },
      d60: { rating: null, areaOfStrength: null, areaOfImprovement: null, comment:"Discipline: Above Average. Suitable for role.", postedOn: "06 Apr 2026", quality: null },
      d90: null,
    },
    nrData: [
      { month: "Jan 2026", val: 305097 },
      { month: "Feb 2026", val: 412843 },
      { month: "Mar 2026", val: 389200 },
    ],
    utilization: [],
    pipStatus: null,
    hrIncidents: [],
    finalStatus: "Confirmed",
  },
  {
    employeeId: "EMP3958",
    name: "Veena Kumari",
    category: "trainer",
    department: "Training Delivery Inhouse",
    doj: "2026-01-10",
    tenureDays: 86,
    reportingManager: "Sakshi Nagpal",
    feedback: {
      d30: { rating: null, areaOfStrength: null, areaOfImprovement: null, comment:"Good trainer. Students give positive reviews.", postedOn: "10 Feb 2026", quality: null },
      d60: { rating: null, areaOfStrength: null, areaOfImprovement: null, comment:"Discipline: Average. Suitable for role: Average.", postedOn: "06 Apr 2026", quality: null },
      d90: null,
    },
    nrData: [],
    utilization: [
      { month: "Jan 2026", val: 71.25 },
      { month: "Feb 2026", val: 82.50 },
      { month: "Mar 2026", val: 79.00 },
    ],
    pipStatus: null,
    hrIncidents: [],
    finalStatus: "In Progress",
  },
  {
    employeeId: "EMP3933",
    name: "Prem Kumar",
    category: "pt",
    department: "",
    doj: "2025-12-15",
    tenureDays: 112,
    reportingManager: "Kanagavalli Joseph Manns",
    feedback: {
      d30: { rating: null, areaOfStrength: null, areaOfImprovement: null, comment:"Showing improvement. Working on feedbacks given.", postedOn: "14 Jan 2026", quality: null },
      d60: { rating: null, areaOfStrength: null, areaOfImprovement: null, comment:"Discipline: Average. Need to improve presentation skills.", postedOn: "13 Feb 2026", quality: null },
      d90: { rating: null, areaOfStrength: null, areaOfImprovement: null, comment:"Coming out of comfort zone. Exploring new skills.", postedOn: "05 Apr 2026", quality: null },
    },
    nrData: [],
    utilization: [],
    pipStatus: { type: "PA", issuedDate: "01 Mar 2026", endDate: "01 Apr 2026" },
    hrIncidents: [
      { type: "neg", comment: "Late submission on project deadline", date: "20 Jan 2026" },
    ],
    finalStatus: "PA Issued",
  },
  {
    employeeId: "EMP3953",
    name: "Shahbaaz Khan",
    category: "trainer",
    department: "Training Delivery Inhouse",
    doj: "2025-12-20",
    tenureDays: 107,
    reportingManager: "Farha Shaikh",
    feedback: {
      d30: { rating: null, areaOfStrength: null, areaOfImprovement: null, comment:"Has potential to do better.", postedOn: "19 Jan 2026", quality: null },
      d60: { rating: null, areaOfStrength: null, areaOfImprovement: null, comment:"Need to be quick in skill upgrade. Prepare well for mocks.", postedOn: "18 Feb 2026", quality: null },
      d90: { rating: null, areaOfStrength: null, areaOfImprovement: null, comment:"Informed leave issue resolved. Improvement noted.", postedOn: "04 Apr 2026", quality: null },
    },
    nrData: [],
    utilization: [
      { month: "Dec 2025", val: 49.00 },
      { month: "Jan 2026", val: 56.00 },
      { month: "Feb 2026", val: 52.50 },
    ],
    pipStatus: { type: "PIP", issuedDate: "15 Feb 2026", endDate: "15 Mar 2026" },
    hrIncidents: [
      { type: "neg", comment: "Uninformed leave taken without prior RMS application", date: "20 Jan 2026" },
    ],
    finalStatus: "PIP Issued",
  },
  {
    employeeId: "EMP3906",
    name: "Priyanka Sahansi",
    category: "sales",
    department: "Sales",
    doj: "2026-01-15",
    tenureDays: 81,
    reportingManager: "Sushma Sharma",
    feedback: {
      d30: { rating: null, areaOfStrength: null, areaOfImprovement: null, comment:"Good attitude. Needs sales training reinforcement.", postedOn: "14 Feb 2026", quality: null },
      d60: { rating: null, areaOfStrength: null, areaOfImprovement: null, comment:"Discipline: Average. Suitable for role: Average.", postedOn: "05 Apr 2026", quality: null },
      d90: null,
    },
    nrData: [
      { month: "Feb 2026", val: 198000 },
      { month: "Mar 2026", val: 225000 },
    ],
    utilization: [],
    pipStatus: null,
    hrIncidents: [
      { type: "pos", comment: "Proactively helped a colleague close a difficult deal", date: "10 Mar 2026" },
    ],
    finalStatus: "In Progress",
  },
];
